import { AppState } from './types';

export const DEFAULT_APP_STATE: AppState = {
  config: {
    logoUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=150', // DJ speaker minimalist logo
    faviconUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=32',
    seoTitle: 'DJ Beat House | Premium Audio Mixing, Remixes & Voice Tags',
    seoDescription: 'Welcome to DJ Beat House. Professional music production, audio mixing, custom DJ voice tags, premium beat packs, and high-quality YouTube resources.',
    seoKeywords: 'DJ voice tag, audio mixing, beat pack, sample pack, YouTube growth tips, DJ Remix, bass boost, voice over, DJ Beat House',
    openGraphImage: 'https://images.unsplash.com/photo-1516873240891-4bf014598ab4?auto=format&fit=crop&q=80&w=1200',
    robotsTxt: 'User-agent: *\nAllow: /',
    sitemapXml: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>https://djbeathouse.com/</loc>\n    <lastmod>2026-07-16</lastmod>\n  </url>\n</urlset>',
    googleAnalyticsId: 'G-XXXXXXXXXX',
    googleSearchConsoleId: 'sc-verify-code',
  },
  home: {
    bannerUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1920',
    title: 'CRAFTING THE FUTURE OF BEATS',
    subtitle: 'Premium Audio Production, DJ Voice Tags, Professional Remixes, and YouTube Growth Resources. Unleash the heavy bass.',
    buttonText: 'EXPLORE OUR SERVICES',
    buttonLink: '#services',
  },
  about: {
    title: 'THE BEAT HOUSE LEGACY',
    description: 'At DJ Beat House, we breathe bass and live for the drop. We are a collective of professional audio engineers, designers, and visual creators dedicated to elevating your music and digital presence. From delivering chest-thumping bass-boosted remixes to crafting custom high-impact DJ voice tags, we provide the ultimate toolkit for DJs, artists, and creators worldwide. Our mission is simple: to make your sound unforgettable and your content legendary.',
    imageUrl: 'https://images.unsplash.com/photo-1516873240891-4bf014598ab4?auto=format&fit=crop&q=80&w=800',
  },
  whyChooseUs: [
    {
      id: 'wcu-1',
      iconName: 'Zap',
      title: 'Ultra-Fast 24-Hour Delivery',
      description: 'We know inspiration doesn\'t wait. Get your custom voice tags, audio mixes, or graphic designs within 24 hours of placing an order.',
    },
    {
      id: 'wcu-2',
      iconName: 'Volume2',
      title: 'Premium Studio Grade Quality',
      description: 'All audio files are produced in a professional acoustic studio and mastered at 320kbps MP3 & 24-bit WAV for ultimate clarity.',
    },
    {
      id: 'wcu-3',
      iconName: 'HeartHandshake',
      title: '100% Satisfaction Guarantee',
      description: 'We work closely with you. We offer unlimited revisions on graphic designs and up to 3 revisions on audio mixing to guarantee perfection.',
    },
    {
      id: 'wcu-4',
      iconName: 'TrendingUp',
      title: 'Optimized for Creator Success',
      description: 'Our assets are specifically engineered to hook listeners, boost engagement, and accelerate your YouTube channel growth.',
    },
  ],
  categories: [
    { id: 'cat-voice-tag', name: 'DJ Voice Tag' },
    { id: 'cat-remix', name: 'Remix' },
    { id: 'cat-audio-mix', name: 'Audio Mixing' },
    { id: 'cat-bass-boost', name: 'Bass Boost' },
    { id: 'cat-thumb-design', name: 'Thumbnail Design' },
    { id: 'cat-voice-over', name: 'Voice Over' },
    { id: 'cat-beat-pack', name: 'Beat Pack' },
    { id: 'cat-sample-pack', name: 'Sample Pack' },
    { id: 'cat-ai-image', name: 'AI Image' },
    { id: 'cat-short-video', name: 'Short Video Edit' },
    { id: 'cat-yt-tips', name: 'YouTube Growth Tips' },
  ],
  services: [
    {
      id: 'svc-1',
      categoryId: 'cat-voice-tag',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600',
      title: 'Custom Female DJ Voice Tag',
      description: 'Sultry, energetic, or high-impact custom vocal drops with world-class reverb, delay, and filter FX. Fully customized with your DJ name.',
      price: '$25',
      isFeatured: true,
      isPublished: true,
    },
    {
      id: 'svc-2',
      categoryId: 'cat-audio-mix',
      imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=600',
      title: 'Professional Multi-Track Mixing',
      description: 'Bring your vocals and instrumental stems to life. Industry-grade EQ, compression, vocal tuning, and spatial width processing.',
      price: '$89',
      isFeatured: true,
      isPublished: true,
    },
    {
      id: 'svc-3',
      categoryId: 'cat-beat-pack',
      imageUrl: 'https://images.unsplash.com/photo-1484755560693-a4074577af3a?auto=format&fit=crop&q=80&w=600',
      title: 'Trap & Drill Ultimate Beat Pack',
      description: '10 exclusive, fully license-free instrumental beats. WAV stems + MIDI patterns included. Elevate your rap and vocal projects.',
      price: '$45',
      isFeatured: true,
      isPublished: true,
    },
    {
      id: 'svc-4',
      categoryId: 'cat-thumb-design',
      imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=600',
      title: 'High-CTR Cyberpunk DJ Thumbnail',
      description: 'A custom, eye-catching YouTube thumbnail design with neon red highlights, custom DJ assets, and high contrast typography.',
      price: '$15',
      isFeatured: false,
      isPublished: true,
    },
    {
      id: 'svc-5',
      categoryId: 'cat-bass-boost',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600',
      title: 'Club-Grade Bass Boost',
      description: 'Give any track the heavy sub-bass treatment without distorting the mids and highs. Optimized specifically for car subwoofers and club setups.',
      price: '$10',
      isFeatured: false,
      isPublished: true,
    },
  ],
  priceList: [
    { id: 'pr-1', title: 'Standard DJ Voice Tag (FX Mix)', subtitle: 'Delivered in 24 hours, WAV & MP3 formats', price: '$20' },
    { id: 'pr-2', title: 'Premium Multi-Voice Drop Combo', subtitle: '3 unique vocal takes, fully processed with FX', price: '$45' },
    { id: 'pr-3', title: 'Single Track Stereo Mastering', subtitle: 'Final polish for streaming platforms (Spotify, Apple)', price: '$35' },
    { id: 'pr-4', title: 'Full Remix Production (Single)', subtitle: 'Complete custom bootleg or remix in your style', price: '$199' },
    { id: 'pr-5', title: 'YouTube Audio Visualizer Design', subtitle: 'Stunning 4K responsive visualizer linked to your audio', price: '$29' },
  ],
  comboPackages: [
    {
      id: 'pkg-1',
      title: 'STARTER DJ CREATOR KIT',
      price: '$59',
      inclusions: [
        '2 Custom Processed DJ Voice Tags',
        '1 High-CTR Neon YouTube Thumbnail',
        '1 Bass-Boosted Stereo Track Master',
        '24-Hour Delivery Guarantee',
      ],
      imageUrl: 'https://images.unsplash.com/photo-1516873240891-4bf014598ab4?auto=format&fit=crop&q=80&w=600',
      buttonLink: '#contact',
    },
    {
      id: 'pkg-2',
      title: 'ULTIMATE PRODUCER BUNDLE',
      price: '$129',
      inclusions: [
        '5 Custom Voice Tags (Dry & FX stems)',
        'Full Multi-track Vocal Mixing & Mastering',
        '3 Custom Header & Thumbnail Artworks',
        'Priority Support & Lifetime File Backups',
      ],
      imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=600',
      buttonLink: '#contact',
    },
  ],
  portfolio: [
    {
      id: 'v-1',
      youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      videoId: 'dQw4w9WgXcQ',
      thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
      title: 'Rick Astley - Never Gonna Give You Up (Official Video)',
      description: 'The legendary masterpiece for testing audio and streaming compatibility.',
      channelName: 'Rick Astley',
      duration: '3:32',
      publishDate: '2009-10-25',
    },
    {
      id: 'v-2',
      youtubeUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      videoId: 'kJQP7kiw5Fk',
      thumbnailUrl: 'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
      title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
      description: 'Massive club remix and bass performance reference.',
      channelName: 'Luis Fonsi',
      duration: '4:41',
      publishDate: '2017-01-13',
    },
  ],
  gallery: [
    { id: 'gal-1', type: 'image', url: 'https://images.unsplash.com/photo-1516873240891-4bf014598ab4?auto=format&fit=crop&q=80&w=800' },
    { id: 'gal-2', type: 'image', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800' },
    { id: 'gal-3', type: 'image', url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=800' },
  ],
  contact: {
    phone: '+91 98765 43210',
    email: 'contact@djbeathouse.com',
    address: 'Studio 101, Red Light Avenue, Music District, Mumbai, MH, India',
    googleMapsLink: 'https://maps.google.com/maps?q=Mumbai&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  payment: {
    phonePeQrUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=300', // Mock QR Code image
    googlePayQrUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=300',
    paytmQrUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=300',
    upiQrUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=300',
    upiId: 'djbeathouse@upi',
  },
  socials: {
    instagram: 'https://www.instagram.com/dj_beat_house?igsh=dXk1b2FhajJyODli',
    youtube: 'https://www.youtube.com/@DJBEATHOUSE1900',
    facebook: 'https://www.facebook.com/share/1KZP3yN7v2/',
    x: 'https://x.com/dj_beat_house',
    whatsapp: 'https://wa.me/919876543210',
    telegram: 'https://t.me/dj_beat_house_official',
  },
  faq: [
    {
      id: 'faq-1',
      question: 'What is a DJ Voice Tag and how do I receive it?',
      answer: 'A DJ voice tag is a unique audio clip featuring custom vocals (usually dry or loaded with echo/reverb effects) that says your DJ name to brand your mixes. Once ordered, we produce the file in our studio and send a high-quality WAV and MP3 download link via your email or WhatsApp.',
    },
    {
      id: 'faq-2',
      question: 'How long does mixing and mastering take?',
      answer: 'Standard turnaround is within 3 days. However, we offer an Ultra-Fast 24-Hour Express delivery option for urgent releases.',
    },
    {
      id: 'faq-3',
      question: 'Are the beat packs royalty-free?',
      answer: 'Yes! All beat packs and sample packs purchased on DJ Beat House are 100% royalty-free for commercial releases, streaming, live performances, and videos.',
    },
  ],
  policies: {
    privacyPolicy: '<h2>Privacy Policy</h2><p>At DJ Beat House, your privacy is our priority. We only collect the minimal personal information necessary to process your orders (such as email, name, or WhatsApp number). We do not sell or share your data with any third parties. Your payments are processed securely, and your custom audio files are kept confidential unless you explicitly authorize us to share them as portfolio work.</p>',
    termsConditions: '<h2>Terms & Conditions</h2><p>By purchasing services or downloads from DJ Beat House, you agree to these terms: Custom voice tags and audio mixes are created based on your custom input. Up to 3 revisions are included free of charge. No refunds are provided once audio production work has been initiated. You maintain complete distribution rights for tracks completed with our beat packs or mixing services.</p>',
  },
  announcement: {
    text: '🎧 SUMMER SALE: GET 20% OFF ON ALL DJ VOICE TAGS AND MIXING BUNDLES! USE CODE: BEATDROP20 🎧',
    isActive: true,
  },
  visitorCount: 1048,
};
